"""Change statiion_url to hourly_forecast_url

Revision ID: 03ade71cadcb
Revises: 4f66461c11d9
Create Date: 2026-04-20 15:44:05.882798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03ade71cadcb'
down_revision: Union[str, Sequence[str], None] = '4f66461c11d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('hourly_forecast_url', sa.String(), nullable=False))
    op.drop_column('locations', 'station_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('station_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('locations', 'hourly_forecast_url')
    # ### end Alembic commands ###
