"""Add high/low to forecasts

Revision ID: 4f66461c11d9
Revises: c07b2d5de827
Create Date: 2026-04-20 14:20:22.543319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f66461c11d9'
down_revision: Union[str, Sequence[str], None] = 'c07b2d5de827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecasts', sa.Column('high', sa.Integer(), nullable=False))
    op.add_column('forecasts', sa.Column('low', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecasts', 'low')
    op.drop_column('forecasts', 'high')
    # ### end Alembic commands ###
